name: "Jira release note Generator"
description: "Jira release notes generator"
author: "Zee"
inputs:
  release_branch:
    required: true
    description: "Release branch"
    default: "default value if applicable"
  base_branch:
    required: true
    description: "Base branch (master / main)"
  jira_host:
    required: true
    description: "Jira host domain"
  jira_email:
    required: true
    description: "Jira token email"
  jira_token:
    required: true
    description: "Jira access token"
  jira_base_url:
    required: true
    description: "Jira Base URL"
  jira_ticket_id_pattern:
    required: true
    description: "Jira Ticket pattern"
  smtp_host:   
    required: false
    description: "SMTP Host"
  smtp_port:   
    required: false
    description: "SMTP Port(Default is 587)"
  smtp_username:   
    required: false
    description: "SMTP Username"
  smtp_password:
    required: false
    description: "SMTP Password"
  from_mail:
    required: false
    description: "Sender Email"
  to_mail:
    required: false
    description: "Receiver Email"  
runs:
  using: "node16"
  main: "dist/index.js"